Update

diff --git a/opennebula/hadoop-stop b/opennebula/hadoop-stop
--- a/opennebula/hadoop-stop
+++ b/opennebula/hadoop-stop
@@ -11,6 +11,8 @@
 #     First version
 #   11-10-2013 JLC
 #     By default use hadoop cluster name from .hadoop/clustername
+#   15-05-2014 JLC
+#     REST options
 
 scriptName="${0##*/}"
 
@@ -22,29 +24,19 @@ scriptName="${0##*/}"
 # Hadoop-on-demand root directory
 HADOOP_ROOT=$HOME/.hadoop-on-demand
 
-# Load config if available (overwrites previous default values)
-if [[ -r $HADOOP_ROOT/config ]]; then
-  . $HADOOP_ROOT/config
-fi
-
-
-# Get default NAME for the cluster to stop from ~/.hadoop-on-demand/clustername
-if [[ -r $HADOOP_ROOT/clustername ]]; then
-  NAME=`cat $HADOOP_ROOT/clustername`
-fi
-
 #
 # Functions
 #
 function printUsage() {
     cat <<EOF
 
-Usage: $scriptName -n <cluster name>
+Usage: $scriptName -c <cluster name>
     
 Stop a Hadoop cluster 
 
 options include:
-    -n cluster name           Name of the cluster to stop: e.g. hadoop-1.1.2-9282
+    -c clusterID              Name of the cluster to stop: e.g. hadoop-1.1.2-9282
+    -R                        REST API mode (only for use within REST service calls)
     -h                        Print help
 
 EOF
@@ -55,9 +47,10 @@ EOF
 #  Read options
 #
 function readOptions() {
-  while getopts ":hn:" opt; do
+  while getopts ":hc:R" opt; do
       case "$opt" in
-          n) NAME=$OPTARG ;;
+          c) CLUSTERID=$OPTARG ;;
+          R) REST="yes" ;;
           h) printUsage; exit 1 ;;
           *) printUsage; exit 1 ;;
       esac
@@ -65,7 +58,7 @@ function readOptions() {
 
   # Check that there are no unparsed options and that we have the options we need
   shift $((OPTIND - 1))
-  if [[ $# != 0 || -z $NAME ]]; then
+  if [[ $# != 0 ]]; then
       printUsage
       exit 1
   fi
@@ -93,14 +86,22 @@ function stopCluster() {
     echo "ERROR: No se ha recibido correctamente el nombre del cluster"
   fi
 
-  echo "Se eliminarán las siguientes máquinas:"
-  onevm list m|grep $LABEL
-
-  # Are you sure?
-  yesno
+  if [[ -z $REST ]]; then
+    # Show the user the list of machines that will be deleted
+    echo "Se eliminarán las siguientes máquinas:"
+    onevm list m|grep $LABEL
+    # Are you sure?
+    yesno
+  fi
+    
 
   # Let's do it
   onevm list m|grep $LABEL|awk '{print $1}'|xargs -l1 onevm delete
+
+  # Let's remove also the clustername file
+  if [[ -r $HADOOP_ROOT/clustername ]]; then
+    rm "$HADOOP_ROOT/clustername"
+  fi
 
 }
 
@@ -110,7 +111,27 @@ function stopCluster() {
 #
 ###############################################################################
 
+# Load config if available (overwrites previous default values)
+if [[ -r $HADOOP_ROOT/config ]]; then
+  . $HADOOP_ROOT/config
+fi
+
+
+
 readOptions "$@"
 
-stopCluster $NAME
+if [[ -z $CLUSTERID ]]; then
+  # Get default NAME for the cluster to stop from ~/.hadoop-on-demand/clustername
+  if [[ -r $HADOOP_ROOT/clustername ]]; then
+    NAME=`cat $HADOOP_ROOT/clustername`
+  fi
+else
+  NAME=hadoop-$CLUSTERID
+fi
 
+if [[ -z $NAME ]];then
+  echo "ERROR: No se ha encontrado el nombre de ningun cluster para parar"
+  exit 2;
+else
+  stopCluster $NAME
+fi
